# http://localhost:8080/swagger-ui/index.html - swagger ui link
config:
  primary-language: "en"
  languages:
      - "ru"
      - "ua"
      - "en"
  keepPeriod: 14
  messageFile: "messages"
  password:
    pepper: "${GLOBAL_PEPPER}"

spring:
  profiles:
    active: "dev"
  datasource:
    url: "jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB_NAME}"
    username: "${MYSQL_DB_USERNAME}"
    password: "${MYSQL_DB_PASSWORD}"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"

management:
  server:
    port: 9090 #required for actuator & swagger-ui working along
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"
  info:
    java:
      enabled: "true"

springdoc:
  swagger-ui:
    tagsSorter: "alpha" #For sorting tags alphabetically
