config:
  primary-language: "en"
  languages:
      - "ru"
      - "ua"
      - "en"

spring:
  profiles:
    active: "dev"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"
  info:
    java:
      enabled: "true"
