spring:
  devtools:
    devtools:
      add-properties: true
    restart:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        transaction: "TRACE"
        org:
          jpa: "DEBUG"
