# http://localhost:8080/swagger-ui/index.html - swagger ui link
config:
  primary-language: "en"
  languages:
      - "ru"
      - "ua"
      - "en"
  keepPeriod: 14
  messageFile: "messages"
  password:
    pepper: "${GLOBAL_PEPPER}"

spring:
  profiles:
    active: "dev"

management:
  server:
    port: 9090 #required for actuator & swagger-ui working along
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"
  info:
    java:
      enabled: "true"

springdoc:
  swagger-ui:
    tagsSorter: "alpha" #For sorting tags alphabetically
