config:
  primary-language: "en"
  languages:
      - "ru"
      - "ua"
      - "en"

spring:
  profiles:
    active: "dev"
  # required for Swagger 3.0.0 working along Spring Boot Actuator
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"
  info:
    java:
      enabled: "true"
